#!/bin/bash
# TurboGears OpenShift post-stop build configuration

set -e
export PYTHON=python-2.6
export PATH=$PATH:~/$PYTHON/virtenv/bin/

source ~/$PYTHON/virtenv/bin/activate


# Have apache serve up all of our static resources
echo "Symlinking static resources from tg2app/public"
ln -s $OPENSHIFT_REPO_DIR/wsgi/tg2app/tg2app/public/* $OPENSHIFT_REPO_DIR/wsgi/static/

cd $OPENSHIFT_REPO_DIR/wsgi/tg2app

# We're not doing 'install' to save space.
python setup.py develop
